baseURL = "https://talk.bmpi.dev"
languageCode = "zh-cn"
title = "BMPI Talks"

disableKinds = ["sitemap", "RSS"]

theme = "reveal-hugo"

[author]
name = "Dawei Ma"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
# we need a style that looks good in both light and dark background!
codeFences = false
style = "tango"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true
custom_theme = "custom-theme.scss"
custom_theme_compile = true

[reveal_hugo.custom_theme_options]
targetPath = "css/custom-theme.css"
enableSourceMap = true

# used in content/template-example
[params.reveal_hugo.templates.grey]
background = "#424242"
transition = "convex"

