[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/2021/i18n-java/*"
  to = "/2021/i18n-java/index.html"
  status = 200

[[redirects]]
  from = "/2020/web-traffic-research/*"
  to = "/2020/web-traffic-research/index.html"
  status = 200

[[redirects]]
  from = "/2019/elixir/*"
  to = "/2019/elixir/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://www.bmpi.dev/talk"
  status = 302