@startmindmap
skinparam monochrome true
* 内容推广
** 写作前
*** 理论
**** 写作的目的
***** 获取关注度
***** 获取影响力
***** 打造个人品牌
**** 文章的类型
***** 入门文章
***** 专业文章
**** 搜索页前几篇文章
***** 文章关键词
***** 文章阅读量
***** 发布平台
***** 作者信息
*** 实践
*** 主题选定
** 写作中
*** 理论
*** 实践
*** 内链设计
** 写作后
*** 理论
**** 选择推广平台
***** 主流平台
***** 平台特点
***** 对平台做测试
*** 实践
*** 确定推广语
@endmindmap
