name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i @slidev/cli@0.22.1 -g

      - run: npm i && npm run build && cp netlify.toml dist/
        env:
          NPM_FLAGS: "--prefix=/dev/null"
          PLAYWRIGHT_BROWSERS_PATH: "0"

      - run: slidev build slides/2021/i18n_java/slides.md --base /2021/i18n-java/ --out dist/2021/i18n-java/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
